# Generated by Django 4.2.1 on 2023-06-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_EshopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
