# Generated by Django 4.2.1 on 2023-06-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_EshopApp', '0002_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='', max_length=250),
        ),
    ]
