# Generated by Django 4.2.1 on 2023-06-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_EshopApp', '0003_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
